[[Configurations]]
  Name = "pgo-generate"
  Root = "$HOME/work/go/"
  PgoGen = "profiles" # Sub-directory where we put profiles
#  Disabled = true

[[Configurations]]
  Name = "pgo-use"
  Root = "$HOME/work/go/"
  PgoUse = "profiles" # Sub-directory where we search profiles
  Disabled = true
