[[Configurations]]
  Name = "Resched"
  GcFlags = "-d=ssa/insert_resched_checks/on"
  RunEnv = ["GOGC=100"]
  RunFlags = ["-test.short"]
  Root = "$HOME/go/"
#  RunWrapper = ["foo"]  # Optional command wrapper
#  Disabled = true       # Don't run this configuration

[[Configurations]]
  Name = "NoResched"
  GcFlags = "-d=ssa/insert_resched_checks/off"
  RunEnv = ["GOGC=100"]
  RunFlags = ["-test.short"]
  Root = "$HOME/go/"
